### ISSUE TITLE
Rokuality find element by text is not working

### ISSUE THREAD

**Issue by anuragstar** [rokuality/rokuality-js#8]
Hi Team,

We tried to run test on Roku, but some of the functionality was not working
 findElementByText was not working, it was returning an empty response.

`Failed to find element with locator type By.Text:  and identifier                   Sign in with Email                   on the device screen.
      17 |     _classCallCheck(this, NoSuchElementException);
      18 |
    > 19 |     var _this = _possibleConstructorReturn(this, (NoSuchElementException.__proto__ || Object.getPrototypeOf(NoSuchElementException)).call(this, message));
      20 |
      21 |     _this.name = _this.constructor.name;
      22 |     return _this;
      at new NoSuchElementException (../build/exceptions/NoSuchElementException.js:19:134)
      at Finder.handler (../build/driver/Finder.js:140:15)
      at Finder.findElement (../build/driver/Finder.js:89:31)
      at Object.<anonymous> (roku.test.js:67:19)

`

**Comment by rokualitysupport** [comment]
Hello, the By.Text locator type is an OCR evaluation that happens against the current screen image and requires either a valid Google Vision account or Amazon Textract/Rekognition account setup with the requisite capabilities. Please see the finding element documation at https://github.com/rokuality/rokuality-js#finding-elements with specific focus on 'Using Google Vision' or 'Using Amazon Rekognition'. If the proper setup isn't done for OCR then passing this locator type won't work. In your logs they'll be logging indicating this effect. If they are setup properly then your logs will contain details about all the matched text via the OCR engine and will include details and bounding box information so you can see what the OCR engines are returning vs what you expect with the locator being passed in. Note that in the next release coming this week we will also support Tesseract as a valid OCR engine which will be a nice open source/free OCR engine that users can leverage if they don't have a valid Google Vision or Amazon Rekognition account.

For Roku specifically, if you want to evaluate the DOM text - you should use the RokuBy.Text locator which does not leverage an underlying OCR engine and uses the page xml returned by Roku webdriver. Please see the documentation section https://github.com/rokuality/rokuality-js#Finding-elements-with-Roku-WebDriver for details of usage.

**Comment by rokualitysupport** [comment]
Rokuality 1.3.2 is now available at https://www.rokuality.com/download which provides support for OCRType 'Tesseract'. If you install tesseract locally, and provide the 'OCRType' capability with value 'Tesseract', and the 'TesseractBinary' capability with value '/path/to/tesseract/binary' then your above By.Text ocr locators should work. It's a nice open source/no cost option for OCR screen evaluations so you don't need to use a paid service like Google Vision or Amazon Rekognition/Textract.

**Comment by rokualitysupport** [comment]
Rokuality client bindings 1.5.2 are now available with support for Tesseract. If used in conjunction with Rokuality app 1.3.2 or higher you should now be able to use Tesseract as an open source OCR alternative and the above mentioned methods for textual locators should work.
